--liquibase formatted sql

--changeset developer:20260110210000-2
CREATE TABLE ods.tbl_chart (
    chart_no BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pt_no VARCHAR(50) NOT NULL,
    label VARCHAR(20) NOT NULL,
    code VARCHAR(50) NOT NULL,
    in_date DATE NOT NULL,
    out_date DATE,
    department VARCHAR(50) NOT NULL,
    doctor VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tbl_chart PRIMARY KEY (chart_no)
);

--changeset developer:20260110210000-4
ALTER TABLE ods.tbl_chart
    ADD CONSTRAINT fk_tbl_chart__pt_no
    FOREIGN KEY (pt_no)
    REFERENCES ods.tbl_patient (pt_no);

--changeset developer:20260110210000-6-data context:faker
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (1, 'P2024001', '외래', 'O', '20260115', '20260115', '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (2, 'P2024001', '외래', 'O', '20260220', '20260220', '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (3, 'P2024002', '외래', 'O', '20260108', '20260108', '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (4, 'P2024003', '응급', 'E', '20260122', '20260122', '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (5, 'P2024004', '외래', 'O', '20260205', '20260205', '피부과', '최의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (6, 'P2024005', '입원', 'I', '20260110', '20260110', '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (7, 'P2024005', '입원', 'I', '20260112', '20260112', '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (8, 'P2024006', '외래', 'O', '20260214', '20260214', '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (9, 'P2024007', '응급', 'E', '20260118', '20260118', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (10, 'P2024008', '외래', 'O', '20260201', '20260201', '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (11, 'P2024009', '외래', 'O', '20260125', '20260125', '이비인후과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (12, 'P2024010', '외래', 'O', '20260210', '20260210', '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (13, 'P2024003', '외래', 'O', '20260228', '20260228', '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (14, 'P2024002', '외래', 'O', '20260305', '20260305', '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (15, 'P2024006', '외래', 'O', '20260312', '20260312', '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (16, 'P2024004', '입원', 'I', '20260103', '20260103', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (17, 'P2024004', '입원', 'I', '20260105', '20260105', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (18, 'P2024004', '입원', 'I', '20260107', '20260107', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (19, 'P2024001', '응급', 'E', '20260120', '20260120', '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (20, 'P2024007', '외래', 'O', '20260203', '20260203', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (21, 'P2024005', '입원', 'I', '20260120', '20260120', '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (22, 'P2024009', '응급', 'E', '20260215', '20260215', '이비인후과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (23, 'P2024010', '입원', 'I', '20260112', '20260112', '내분비내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (24, 'P2024008', '외래', 'O', '20260128', '20260128', '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (25, 'P2024003', '외래', 'O', '20260105', '20260105', '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (26, 'P2024006', '외래', 'O', '20260118', '20260118', '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (27, 'P2024002', '외래', 'O', '20260125', '20260125', '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (28, 'P2024007', '응급', 'E', '20260112', '20260112', '응급의학과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (29, 'P2024008', '외래', 'O', '20260115', '20260115', '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (30, 'P2024009', '외래', 'O', '20260130', '20260130', '이비인후과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (31, 'P2024010', '외래', 'O', '20260122', '20260122', '내분비내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (32, 'P2024001', '외래', 'O', '20260128', '20260128', '심장내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (33, 'P2024004', '외래', 'O', '20260120', '20260120', '피부과', '최의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (34, 'P2024005', '입원', 'I', '20260205', '20260205', '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (35, 'P2024006', '외래', 'O', '20260122', '20260122', '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (36, 'P2024003', '외래', 'O', '20260210', '20260210', '재활의학과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (37, 'P2024007', '외래', 'O', '20260125', '20260125', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (38, 'P2024002', '외래', 'O', '20260212', '20260212', '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (39, 'P2024008', '외래', 'O', '20260208', '20260208', '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (40, 'P2024009', '응급', 'E', '20260220', '20260220', '응급의학과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (41, 'P2024010', '입원', 'I', '20260215', '20260215', '내분비내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (42, 'P2024001', '외래', 'O', '20260218', '20260218', '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (43, 'P2024004', '외래', 'O', '20260222', '20260222', '피부과', '최의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (44, 'P2024005', '입원', 'I', '20260228', '20260228', '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (45, 'P2024006', '외래', 'O', '20260225', '20260225', '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (46, 'P2024003', '외래', 'O', '20260218', '20260218', '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (47, 'P2024007', '외래', 'O', '20260220', '20260220', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (48, 'P2024002', '외래', 'O', '20260228', '20260228', '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (49, 'P2024008', '응급', 'E', '20260222', '20260222', '응급의학과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (50, 'P2024009', '외래', 'O', '20260301', '20260301', '이비인후과', '임의사');
