--liquibase formatted sql

--changeset developer:20260110210000-1
CREATE TABLE ods.tbl_patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pt_no VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    sex VARCHAR(10) NOT NULL,
    age INTEGER NOT NULL,
    resident_no1 VARCHAR(6) NOT NULL,
    resident_no2 VARCHAR(7) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tbl_patient PRIMARY KEY (id),
    CONSTRAINT uk_tbl_patient_pt_no UNIQUE (pt_no)
);

--changeset developer:20260110210000-5-data context:faker
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (1, 'P2024001', '김철수', '남', 45, '701215', '1234567');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (2, 'P2024002', '이영희', '여', 32, '920323', '2345678');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (3, 'P2024003', '박민수', '남', 58, '660512', '1456789');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (4, 'P2024004', '최지연', '여', 28, '960815', '2567890');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (5, 'P2024005', '정동욱', '남', 67, '571201', '1678901');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (6, 'P2024006', '강미영', '여', 41, '831022', '2789012');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (7, 'P2024007', '한상철', '남', 52, '720618', '1890123');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (8, 'P2024008', '윤서연', '여', 24, '000925', '2901234');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (9, 'P2024009', '임준호', '남', 39, '851104', '1012345');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (10, 'P2024010', '송하나', '여', 61, '630730', '2123456');
