--liquibase formatted sql

--changeset developer:20260110210000-0
CREATE SCHEMA IF NOT EXISTS ods;

--changeset developer:20260110210000-1
CREATE TABLE ods.tbl_patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pt_no VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    sex VARCHAR(10) NOT NULL,
    age INTEGER NOT NULL,
    resident_no1 VARCHAR(6) NOT NULL,
    resident_no2 VARCHAR(7) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tbl_patient PRIMARY KEY (id),
    CONSTRAINT uk_tbl_patient_pt_no UNIQUE (pt_no)
);

--changeset developer:20260110210000-2
CREATE TABLE ods.tbl_chart (
    chart_no BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pt_no VARCHAR(50) NOT NULL,
    label VARCHAR(20) NOT NULL,
    code VARCHAR(50) NOT NULL,
    in_date DATE NOT NULL,
    out_date DATE,
    department VARCHAR(50) NOT NULL,
    doctor VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tbl_chart PRIMARY KEY (chart_no)
);

--changeset developer:20260110210000-4
ALTER TABLE ods.tbl_chart
    ADD CONSTRAINT fk_tbl_chart__pt_no
    FOREIGN KEY (pt_no)
    REFERENCES ods.tbl_patient (pt_no);

--changeset developer:20260110210000-5-data context:faker
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (1, 'P2024001', '김철수', '남', 45, '701215', '1234567');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (2, 'P2024002', '이영희', '여', 32, '920323', '2345678');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (3, 'P2024003', '박민수', '남', 58, '660512', '1456789');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (4, 'P2024004', '최지연', '여', 28, '960815', '2567890');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (5, 'P2024005', '정동욱', '남', 67, '571201', '1678901');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (6, 'P2024006', '강미영', '여', 41, '831022', '2789012');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (7, 'P2024007', '한상철', '남', 52, '720618', '1890123');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (8, 'P2024008', '윤서연', '여', 24, '000925', '2901234');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (9, 'P2024009', '임준호', '남', 39, '851104', '1012345');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (10, 'P2024010', '송하나', '여', 61, '630730', '2123456');

--changeset developer:20260110210000-6-data context:faker
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (1, 'P2024001', '외래', 'O', '2026-01-15', NULL, '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (2, 'P2024001', '외래', 'O', '2026-02-20', NULL, '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (3, 'P2024002', '외래', 'O', '2026-01-08', NULL, '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (4, 'P2024003', '응급', 'E', '2026-01-22', NULL, '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (5, 'P2024004', '외래', 'O', '2026-02-05', NULL, '피부과', '최의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (6, 'P2024005', '입원', 'I', '2026-01-10', NULL, '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (7, 'P2024005', '입원', 'I', '2026-01-12', NULL, '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (8, 'P2024006', '외래', 'O', '2026-02-14', NULL, '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (9, 'P2024007', '응급', 'E', '2026-01-18', NULL, '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (10, 'P2024008', '외래', 'O', '2026-02-01', NULL, '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (11, 'P2024009', '외래', 'O', '2026-01-25', NULL, '이비인후과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (12, 'P2024010', '외래', 'O', '2026-02-10', NULL, '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (13, 'P2024003', '외래', 'O', '2026-02-28', NULL, '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (14, 'P2024002', '외래', 'O', '2026-03-05', NULL, '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (15, 'P2024006', '외래', 'O', '2026-03-12', NULL, '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (16, 'P2024004', '입원', 'I', '2026-01-03', NULL, '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (17, 'P2024004', '입원', 'I', '2026-01-05', NULL, '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (18, 'P2024004', '입원', 'I', '2026-01-07', NULL, '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (19, 'P2024001', '응급', 'E', '2026-01-20', NULL, '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (20, 'P2024007', '외래', 'O', '2026-02-03', NULL, '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (21, 'P2024005', '입원', 'I', '2026-01-20', NULL, '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (22, 'P2024009', '응급', 'E', '2026-02-15', NULL, '이비인후과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (23, 'P2024010', '입원', 'I', '2026-01-12', NULL, '내분비내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (24, 'P2024008', '외래', 'O', '2026-01-28', NULL, '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (25, 'P2024003', '외래', 'O', '2026-01-05', NULL, '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (26, 'P2024006', '외래', 'O', '2026-01-18', NULL, '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (27, 'P2024002', '외래', 'O', '2026-01-25', NULL, '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (28, 'P2024007', '응급', 'E', '2026-01-12', NULL, '응급의학과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (29, 'P2024008', '외래', 'O', '2026-01-15', NULL, '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (30, 'P2024009', '외래', 'O', '2026-01-30', NULL, '이비인후과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (31, 'P2024010', '외래', 'O', '2026-01-22', NULL, '내분비내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (32, 'P2024001', '외래', 'O', '2026-01-28', NULL, '심장내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (33, 'P2024004', '외래', 'O', '2026-01-20', NULL, '피부과', '최의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (34, 'P2024005', '입원', 'I', '2026-02-05', NULL, '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (35, 'P2024006', '외래', 'O', '2026-01-22', NULL, '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (36, 'P2024003', '외래', 'O', '2026-02-10', NULL, '재활의학과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (37, 'P2024007', '외래', 'O', '2026-01-25', NULL, '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (38, 'P2024002', '외래', 'O', '2026-02-12', NULL, '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (39, 'P2024008', '외래', 'O', '2026-02-08', NULL, '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (40, 'P2024009', '응급', 'E', '2026-02-20', NULL, '응급의학과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (41, 'P2024010', '입원', 'I', '2026-02-15', NULL, '내분비내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (42, 'P2024001', '외래', 'O', '2026-02-18', NULL, '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (43, 'P2024004', '외래', 'O', '2026-02-22', NULL, '피부과', '최의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (44, 'P2024005', '입원', 'I', '2026-02-28', NULL, '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (45, 'P2024006', '외래', 'O', '2026-02-25', NULL, '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (46, 'P2024003', '외래', 'O', '2026-02-18', NULL, '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (47, 'P2024007', '외래', 'O', '2026-02-20', NULL, '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (48, 'P2024002', '외래', 'O', '2026-02-28', NULL, '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (49, 'P2024008', '응급', 'E', '2026-02-22', NULL, '응급의학과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (50, 'P2024009', '외래', 'O', '2026-03-01', NULL, '이비인후과', '임의사');

--changeset developer:20260110210000-7-fix context:faker
CREATE TABLE ods.tbl_category_intpatient1 (
    n VARCHAR(1), -- 방사선
    m VARCHAR(1), -- 미생물
    l VARCHAR(1), -- 진검
    p VARCHAR(1) -- 병리
);
insert into ods.tbl_category_intpatient1 (n, m, l, p) values ('Y', 'Y', 'Y', 'Y');

CREATE TABLE ods.tbl_category_intpatient2 (
    e VARCHAR(1), -- 영상
    f VARCHAR(1), -- 내시경
    g VARCHAR(1), -- 기능
    h VARCHAR(1) -- 핵의학
);
insert into ods.tbl_category_intpatient2 (e, f, g, h) values ('Y', 'Y', 'Y', 'Y');

