--liquibase formatted sql

--changeset developer:20260110210000-0
CREATE SCHEMA IF NOT EXISTS ods;

--changeset developer:20260110210000-1
CREATE TABLE ods.tbl_patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pt_no VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    sex VARCHAR(10) NOT NULL,
    age INTEGER NOT NULL,
    resident_no1 VARCHAR(6) NOT NULL,
    resident_no2 VARCHAR(7) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tbl_patient PRIMARY KEY (id),
    CONSTRAINT uk_tbl_patient_pt_no UNIQUE (pt_no)
);

--changeset developer:20260110210000-2
CREATE TABLE ods.tbl_chart (
    chart_no BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pt_no VARCHAR(50) NOT NULL,
    label VARCHAR(20) NOT NULL,
    code VARCHAR(50) NOT NULL,
    in_date DATE NOT NULL,
    out_date DATE,
    department VARCHAR(50) NOT NULL,
    doctor VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tbl_chart PRIMARY KEY (chart_no)
);

--changeset developer:20260110210000-4
ALTER TABLE ods.tbl_chart
    ADD CONSTRAINT fk_tbl_chart__pt_no
    FOREIGN KEY (pt_no)
    REFERENCES ods.tbl_patient (pt_no);

--changeset developer:20260110210000-5-data context:faker
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (1, 'P2024001', '김철수', '남', 45, '701215', '1234567');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (2, 'P2024002', '이영희', '여', 32, '920323', '2345678');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (3, 'P2024003', '박민수', '남', 58, '660512', '1456789');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (4, 'P2024004', '최지연', '여', 28, '960815', '2567890');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (5, 'P2024005', '정동욱', '남', 67, '571201', '1678901');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (6, 'P2024006', '강미영', '여', 41, '831022', '2789012');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (7, 'P2024007', '한상철', '남', 52, '720618', '1890123');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (8, 'P2024008', '윤서연', '여', 24, '000925', '2901234');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (9, 'P2024009', '임준호', '남', 39, '851104', '1012345');
INSERT INTO ods.tbl_patient (id, pt_no, name, sex, age, resident_no1, resident_no2) VALUES (10, 'P2024010', '송하나', '여', 61, '630730', '2123456');

--changeset developer:20260110210000-6-data context:faker
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (1, 'P2024001', '외래', 'O', '20260115', '20260115', '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (2, 'P2024001', '외래', 'O', '20260220', '20260220', '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (3, 'P2024002', '외래', 'O', '20260108', '20260108', '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (4, 'P2024003', '응급', 'E', '20260122', '20260122', '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (5, 'P2024004', '외래', 'O', '20260205', '20260205', '피부과', '최의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (6, 'P2024005', '입원', 'I', '20260110', '20260110', '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (7, 'P2024005', '입원', 'I', '20260112', '20260112', '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (8, 'P2024006', '외래', 'O', '20260214', '20260214', '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (9, 'P2024007', '응급', 'E', '20260118', '20260118', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (10, 'P2024008', '외래', 'O', '20260201', '20260201', '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (11, 'P2024009', '외래', 'O', '20260125', '20260125', '이비인후과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (12, 'P2024010', '외래', 'O', '20260210', '20260210', '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (13, 'P2024003', '외래', 'O', '20260228', '20260228', '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (14, 'P2024002', '외래', 'O', '20260305', '20260305', '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (15, 'P2024006', '외래', 'O', '20260312', '20260312', '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (16, 'P2024004', '입원', 'I', '20260103', '20260103', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (17, 'P2024004', '입원', 'I', '20260105', '20260105', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (18, 'P2024004', '입원', 'I', '20260107', '20260107', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (19, 'P2024001', '응급', 'E', '20260120', '20260120', '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (20, 'P2024007', '외래', 'O', '20260203', '20260203', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (21, 'P2024005', '입원', 'I', '20260120', '20260120', '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (22, 'P2024009', '응급', 'E', '20260215', '20260215', '이비인후과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (23, 'P2024010', '입원', 'I', '20260112', '20260112', '내분비내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (24, 'P2024008', '외래', 'O', '20260128', '20260128', '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (25, 'P2024003', '외래', 'O', '20260105', '20260105', '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (26, 'P2024006', '외래', 'O', '20260118', '20260118', '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (27, 'P2024002', '외래', 'O', '20260125', '20260125', '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (28, 'P2024007', '응급', 'E', '20260112', '20260112', '응급의학과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (29, 'P2024008', '외래', 'O', '20260115', '20260115', '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (30, 'P2024009', '외래', 'O', '20260130', '20260130', '이비인후과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (31, 'P2024010', '외래', 'O', '20260122', '20260122', '내분비내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (32, 'P2024001', '외래', 'O', '20260128', '20260128', '심장내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (33, 'P2024004', '외래', 'O', '20260120', '20260120', '피부과', '최의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (34, 'P2024005', '입원', 'I', '20260205', '20260205', '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (35, 'P2024006', '외래', 'O', '20260122', '20260122', '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (36, 'P2024003', '외래', 'O', '20260210', '20260210', '재활의학과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (37, 'P2024007', '외래', 'O', '20260125', '20260125', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (38, 'P2024002', '외래', 'O', '20260212', '20260212', '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (39, 'P2024008', '외래', 'O', '20260208', '20260208', '소아과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (40, 'P2024009', '응급', 'E', '20260220', '20260220', '응급의학과', '임의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (41, 'P2024010', '입원', 'I', '20260215', '20260215', '내분비내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (42, 'P2024001', '외래', 'O', '20260218', '20260218', '내과', '김의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (43, 'P2024004', '외래', 'O', '20260222', '20260222', '피부과', '최의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (44, 'P2024005', '입원', 'I', '20260228', '20260228', '신경과', '정의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (45, 'P2024006', '외래', 'O', '20260225', '20260225', '안과', '강의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (46, 'P2024003', '외래', 'O', '20260218', '20260218', '정형외과', '이의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (47, 'P2024007', '외래', 'O', '20260220', '20260220', '외과', '한의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (48, 'P2024002', '외래', 'O', '20260228', '20260228', '산부인과', '박의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (49, 'P2024008', '응급', 'E', '20260222', '20260222', '응급의학과', '윤의사');
INSERT INTO ods.tbl_chart (chart_no, pt_no, label, code, in_date, out_date, department, doctor) VALUES (50, 'P2024009', '외래', 'O', '20260301', '20260301', '이비인후과', '임의사');

--changeset developer:20260110210000-7-fix context:faker
CREATE TABLE ods.tbl_category_intpatient1 (
    n VARCHAR(1), -- 방사선
    m VARCHAR(1), -- 미생물
    l VARCHAR(1), -- 진검
    p VARCHAR(1), -- 병리
    pt_no varchar,
    in_date varchar,
    out_date varchar
);
insert into ods.tbl_category_intpatient1 (n, m, l, p) values ('Y', 'Y', 'Y', 'Y');

CREATE TABLE ods.tbl_category_intpatient2 (
    e VARCHAR(1), -- 영상
    f VARCHAR(1), -- 내시경
    g VARCHAR(1), -- 기능
    h VARCHAR(1), -- 핵의학
    pt_no varchar,
    in_date varchar,
    out_date varchar

);
insert into ods.tbl_category_intpatient2 (e, f, g, h) values ('Y', 'Y', 'Y', 'Y');

CREATE TABLE ods.tbl_category_outpatient1 (
    n VARCHAR(1), -- 방사선
    m VARCHAR(1), -- 미생물
    l VARCHAR(1), -- 진검
    p VARCHAR(1), -- 병리
    pt_no varchar,
    in_date varchar,
    out_date varchar
);
insert into ods.tbl_category_outpatient1 (n, m, l, p) values ('Y', 'Y', 'Y', 'Y');

CREATE TABLE ods.tbl_category_outpatient2 (
    e VARCHAR(1), -- 영상
    f VARCHAR(1), -- 내시경
    g VARCHAR(1), -- 기능
    h VARCHAR(1), -- 핵의학
    pt_no varchar,
    in_date varchar,
    out_date varchar

);
insert into ods.tbl_category_outpatient2 (e, f, g, h) values ('Y', 'Y', 'Y', 'Y');





--changeset developer:20260110210000-8
CREATE TABLE ods.tbl_form (
    ID VARCHAR(1) NOT NULL,
    INDXNM VARCHAR(200) NOT NULL,
    FORMNM VARCHAR(200) NOT NULL,
    ITEMINDXSEQ BIGINT NOT NULL,
    SUPITEMINDXSEQ BIGINT NOT NULL,
    CNT INTEGER NOT NULL,
    EMRFLAG VARCHAR(1) NOT NULL,
    RECKIND VARCHAR(20) NOT NULL,
    SIGNNO VARCHAR(30) NOT NULL,
    LISFLAG VARCHAR(20),
    LEVL INTEGER NOT NULL,
    SECONDSORTNO BIGINT NOT NULL,
    FIRSTSORTNO BIGINT NOT NULL,
    THIRDSORTNO BIGINT NOT NULL,
    CONSTRAINT pk_tbl_form PRIMARY KEY (ID, ITEMINDXSEQ)
);

--changeset developer:20260110210000-9-data context:faker
INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('M', '미생물 검사 보고서', '미생물 검사 보고서', 152749, 0, 1, 'E', 'LIS', '0', NULL, 1, 7, 102, 99999999999);
INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('M', '-', '미생물 검사 보고서', 152752, 152749, 1, 'E', 'LIS', '10000000000800004097', NULL, 2, 9999999999, 9999999999, 10);
INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('L', '진단검사 결과보고서', '진단검사 결과보고서', 152748, 0, 1, 'E', 'LIS', '0', NULL, 1, 6, 102, 99999999999);
INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('L', '-', '진단검사 결과보고서', 152751, 152748, 1, 'E', 'LIS', '10000000000800004096', NULL, 2, 9999999999, 9999999999, 10);

--changeset developer:20260110210000-10-data context:faker
INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('N', '방사선 검사 보고서', '방사선 검사 보고서', 152760, 0, 1, 'E', 'LIS', '0', NULL, 1, 1, 102, 99999999999);
INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('N', '-', '방사선 검사 보고서', 152761, 152760, 1, 'E', 'LIS', '10000000000800004098', NULL, 2, 9999999999, 9999999999, 10);

INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('P', '병리 검사 보고서', '병리 검사 보고서', 152762, 0, 1, 'E', 'LIS', '0', NULL, 1, 4, 102, 99999999999);
INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('P', '-', '병리 검사 보고서', 152763, 152762, 1, 'E', 'LIS', '10000000000800004099', NULL, 2, 9999999999, 9999999999, 10);

INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('E', '영상 검사 보고서', '영상 검사 보고서', 152764, 0, 1, 'E', 'LIS', '0', NULL, 1, 5, 102, 99999999999);
INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('E', '-', '영상 검사 보고서', 152765, 152764, 1, 'E', 'LIS', '10000000000800004100', NULL, 2, 9999999999, 9999999999, 10);

INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('F', '내시경 검사 보고서', '내시경 검사 보고서', 152766, 0, 1, 'E', 'LIS', '0', NULL, 1, 8, 102, 99999999999);
INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('F', '-', '내시경 검사 보고서', 152767, 152766, 1, 'E', 'LIS', '10000000000800004101', NULL, 2, 9999999999, 9999999999, 10);

INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('G', '기능 검사 보고서', '기능 검사 보고서', 152768, 0, 1, 'E', 'LIS', '0', NULL, 1, 9, 102, 99999999999);
INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('G', '-', '기능 검사 보고서', 152769, 152768, 1, 'E', 'LIS', '10000000000800004102', NULL, 2, 9999999999, 9999999999, 10);

INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('H', '의무기록 보고서', '의무기록 보고서', 152770, 0, 1, 'E', 'LIS', '0', NULL, 1, 10, 102, 99999999999);
INSERT INTO ods.tbl_form (ID, INDXNM, FORMNM, ITEMINDXSEQ, SUPITEMINDXSEQ, CNT, EMRFLAG, RECKIND, SIGNNO, LISFLAG, LEVL, SECONDSORTNO, FIRSTSORTNO, THIRDSORTNO)
VALUES ('H', '-', '의무기록 보고서', 152771, 152770, 1, 'E', 'LIS', '10000000000800004103', NULL, 2, 9999999999, 9999999999, 10);
